version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DatabaseERP
  web:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Web.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DBContext=Host=localhost;Port=5432;Database=DatabaseERP;Username=postgres;Password=postgres
  frontend:
    build:
      context: ./ForpostFrontend/react-intro
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://host.docker.internal:8080
      - NODE_OPTIONS=--openssl-legacy-provider
    volumes:
      - ./ForpostFrontend/react-intro:/app
      - /app/node_modules
    stdin_open: true
    tty: true
