version: '3.7'

services:
  db:
    container_name: 'ErpDatabase'
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: npa
      POSTGRES_USER: npa
      POSTGRES_DB: ErpDatabase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  back:
    container_name: 'ForpostApi'
    depends_on:
      db:
        condition: service_healthy
      seq:
        condition: service_started     
    build:
      dockerfile: Web.Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - ./seq-data:/data
#  frontend:
#    build:
#      context: ./ForpostFrontend/react-intro
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    environment:
#      - CHOKIDAR_USEPOLLING=true
#      - REACT_APP_API_URL=http://host.docker.internal:8080
#      - NODE_OPTIONS=--openssl-legacy-provider
#    volumes:
#      - ./ForpostFrontend/react-intro:/app
#      - /app/node_modules
#    stdin_open: true
#    tty: true

